version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0
    steps:
      - checkout
      - run:
          name: Dependencies
          command: bundle install
      - run:
          name: Test
          command: bundle exec rspec spec
      - run:
          name: Upload Test Coverage
          command: COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN  bundle exec coveralls push
